# Generated by Django 2.1.4 on 2022-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la_parrilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meats',
            name='preparation_time',
            field=models.IntegerField(),
        ),
    ]
